export const ADD:string= "ADD"
export const REMOVE:string= "REMOVE"
export const FILTER:string= "FILTER"
export const CHANGE_PAGINATION:string= "CHANGE_PAGINATION"
export const SET_DATA:string= "SET_DATA"
export const SET_MESSAGE:string = "SET_MESSAGE"